version: '3.1'

services: 

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    restart: always
    ports: 
      - 9200:9200
    container_name: elasticsearch
    networks: 
      - elknet

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.0
    restart: always
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports: 
      - 5601:5601
    container_name: kibana
    networks: 
      - elknet

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.3.0
    restart: always
    ports: 
      - 5044:5044
    volumes:
      - $PWD/logstash/confs/:/usr/share/logstash/pipeline/
      - $PWD/logstash/logs/:/logs/
    container_name: logstash
    networks: 
      - elknet
networks:
  elknet:
