--
-- PostgreSQL database cluster dump
--

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE halo;
ALTER ROLE halo WITH SUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'md5b011729a5f87994e502dde4b8c6c5944';
CREATE ROLE halo_anon;
ALTER ROLE halo_anon WITH NOSUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'md571ab4d0532f97b7f1c8d524dc68fe5e9';

--
-- Database creation
--

CREATE DATABASE halo WITH TEMPLATE = template0 OWNER = halo;
REVOKE CONNECT,TEMPORARY ON DATABASE template1 FROM PUBLIC;
GRANT CONNECT ON DATABASE template1 TO PUBLIC;


\connect halo

SET default_transaction_read_only = off;

--
-- PostgreSQL database dump
--

-- Dumped from database version 10.4
-- Dumped by pg_dump version 10.4 (Ubuntu 10.4-0ubuntu0.18.04)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: naturalpersons; Type: TABLE; Schema: public; Owner: postgres
--
--     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
CREATE TABLE public.naturalpersons (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gender character varying(25),
    salutation character varying(50),
    firstnames character varying(50),
    surname character varying(50),
    dateofbirth timestamp without time zone,
    homephonenumber character varying(20),
    workphonenumber character varying(20),
    cellphonenumber character varying(20),
    emailaddress character varying(50)
);


ALTER TABLE public.naturalpersons OWNER TO halo;

grant select on public.naturalpersons to halo_anon;

--
-- Data for Name: naturalpersons; Type: TABLE DATA; Schema: public; Owner: halo
--

COPY public.naturalpersons (gender, salutation, firstnames, surname, dateofbirth, homephonenumber, workphonenumber, cellphonenumber, emailaddress) FROM stdin;
Male	Mr	John Jones	Doe	1949-02-19 00:00:00	0315545665	0315545665	0825545665	john@doe.co.za
Male	Mr	James Dean	Masters	1954-02-12 00:00:00	0315545623	0315545623	0825545623	james.dean@masters.co.za
Female	Miss	Jennifer 	James	1991-01-31 00:00:00	0315545003	0315545003	0815545003	jennifer@james.co.za
Female	Mrs	Khanya	Zulu	1990-08-11 00:00:00	0315522003	0315522003	0725522003	
\.
