version: '3.1'

services:

  postgres:
    image: postgres:10.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: halopass
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    container_name: postgres
    networks: 
      - pgnet
  postgrest:
    image: postgrest/postgrest
    restart: always
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://halo:halopass@postgres:5432/halo
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: halo_anon
    depends_on:
      - postgres
    container_name: postgrest
    networks: 
      - pgnet
  apidocs:
    image: swaggerapi/swagger-ui
    restart: always
    environment: 
      API_URL: http://localhost:3000
    container_name: apidocs
    network_mode:  host
volumes:
  pgdata:
networks: 
  pgnet: